- name: for weblogic
  remote_user: root
  hosts: all
  tasks:
    - name: Execute the script
      command: sh /WLS_DOMAIN/PROD/Oracle/Middleware/Oracle_Home/user_projects/domains/PROD/bin/startWebLogic.sh
